# Generated by Django 2.1.4 on 2019-01-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateField(null=True)),
                ('author', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('book_type', models.PositiveSmallIntegerField(choices=[(1, 'Hardcover'), (2, 'Paperback'), (3, 'E-book')])),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=15)),
                ('Star', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=100)),
                ('PhoneNum', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelId', models.IntegerField()),
                ('URL', models.ImageField(upload_to='')),
                ('URL1', models.ImageField(upload_to='')),
                ('URL2', models.ImageField(upload_to='')),
                ('URL3', models.ImageField(upload_to='')),
                ('URL4', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='hotel_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfRooms', models.IntegerField()),
                ('singleId', models.IntegerField()),
                ('vipId', models.IntegerField()),
                ('suitId', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='near_places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelId', models.IntegerField()),
                ('near_place', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=25)),
                ('personId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('hotel_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='single_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to='')),
                ('numberofrooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='suit_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to='')),
                ('numberofrooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNum', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='vip_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(upload_to='')),
                ('numberofrooms', models.IntegerField()),
            ],
        ),
    ]
